services:
  backend:
    build:
      context: ./cattleDB
      dockerfile: Dockerfile  # Ensure this Dockerfile exists
    container_name: springboot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./cattle-admin
      dockerfile: Dockerfile  # Ensure this Dockerfile exists
    container_name: vite-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

