services:
  backend:
    build:
      context: ./cattleDB
      # dockerfile: Dockerfile-spring-boot
    container_name: springboot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./cattle-admin # Ensure this path exists
      # dockerfile: Dockerfile-vite
    container_name: vite-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
