----liquibase formatted sql
--
---- changeset yourname:create_users_table

alter table if exists beacon_attributes 
   drop constraint if exists FKetmnlsb244lhjo5lxteiwy2n9;
alter table if exists device_active_geofences 
   drop constraint if exists FKcwnmkhcbprpdlhtdcev5pobqm;pwd

alter table if exists device_asn_configs 
   drop constraint if exists FK2kwc0b338ko0ik7amjswsupwd;
alter table if exists device_geofences 
   drop constraint if exists FK26s5uklcaggr74e84b5bi95ny;
alter table if exists device_notifications 
   drop constraint if exists FKipv2okwkoyl4nkrp342rtaf5o;
drop table if exists beacon cascade;
drop table if exists beacon_attributes cascade;
drop table if exists cron_job_logs cascade;
drop table if exists csv_entity cascade;
drop table if exists device cascade;
drop table if exists device_active_geofences cascade;
drop table if exists device_asn_configs cascade;
drop table if exists device_geofences cascade;
drop table if exists device_notifications cascade;
drop table if exists event_entity cascade;
drop table if exists route_entity cascade;
drop table if exists summary cascade;
create table beacon (
    battery_level integer,
    latitude float(53);,
    longitude float(53);,
    major integer not null,
    minor integer not null,
    relative boolean not null,
    device_id bigint,
    id bigint generated by default as identity,
    last_seen timestamp(6); with time zone,
    role_group_id bigint,
    name varchar(255);,
    uuid varchar(255);,
    primary key (id);
);
create table beacon_attributes (
    beacon_id bigint not null,
    attribute_name varchar(255); not null,
    attribute_value TEXT,
    primary key (beacon_id, attribute_name);
);
create table cron_job_logs (
    duration_ms bigint,
    id bigint generated by default as identity,
    end_time varchar(255);,
    error_message varchar(255);,
    job_name varchar(255);,
    start_time varchar(255);,
    status varchar(255);,
    primary key (id);
);
create table csv_entity (
    latitude float(53); not null,
    longitude float(53); not null,
    major integer not null,
    minor integer not null,
    valid boolean not null,
    id bigint generated by default as identity,
    altitude varchar(255);,
    attributes varchar(255);,
    filename varchar(255);,
    geofences varchar(255);,
    location_beacon varchar(255);,
    speed varchar(255);,
    time varchar(255);,
    uuid varchar(255);,
    primary key (id);
);
create table device (
    all_geofences_enabled boolean,
    battery_level integer,
    disabled boolean not null,
    first_data_time timestamp(6); with time zone,
    id bigint generated by default as identity,
    last_asn_cookie timestamp(6); with time zone,
    last_attempt timestamp(6); with time zone,
    last_incomplete_asn_job timestamp(6); with time zone,
    last_successful_asn_job timestamp(6); with time zone,
    last_update timestamp(6); with time zone,
    position_id bigint,
    category varchar(255);,
    contact varchar(255);,
    firmware_version varchar(255);,
    last_asn_fail varchar(255);,
    last_one_time_job varchar(255);,
    leaf_group_name varchar(255);,
    model varchar(255);,
    name varchar(255);,
    phone varchar(255);,
    status varchar(255);,
    unique_id varchar(255);,
    primary key (id);
);
create table device_active_geofences (
    active_geofences bigint,
    device_id bigint not null
);
create table device_asn_configs (
    asn_configs bigint,
    device_id bigint not null
);
create table device_geofences (
    device_id bigint not null,
    geofences bigint
);
create table device_notifications (
    device_id bigint not null,
    notifications bigint
);
create table event_entity (
    beacon_major integer,
    beacon_minor integer,
    beacon_id bigint,
    device_id bigint,
    device_time timestamp(6); with time zone,
    geofence_id bigint,
    id bigint generated by default as identity,
    position_id bigint,
    server_time timestamp(6); with time zone,
    trackable_id bigint,
    user_id bigint,
    beacon_name varchar(255);,
    beacon_uuid varchar(255);,
    message varchar(255);,
    name varchar(255);,
    type varchar(255);,
    primary key (id);
);
create table route_entity (
    beacon_major integer,
    beacon_minor integer,
    latitude float(53);,
    longitude float(53);,
    outdated boolean not null,
    rssi integer,
    scan_rssi integer,
    valid boolean not null,
    beacon_id bigint,
    device_id bigint,
    device_time timestamp(6); with time zone,
    event_id bigint,
    fix_time timestamp(6); with time zone,
    id bigint generated by default as identity,
    server_time timestamp(6); with time zone,
    source_device_id bigint,
    beacon_name varchar(255);,
    beacon_uuid varchar(255);,
    device_name varchar(255);,
    name varchar(255);,
    protocol varchar(255);,
    primary key (id);
);
create table summary (
    average_speed float(53);,
    beacon_count integer,
    distance float(53);,
    end_odometer float(53);,
    engine_hours float(53);,
    max_speed float(53);,
    position_count integer,
    spent_fuel float(53);,
    start_odometer float(53);,
    device_id bigint,
    id bigint generated by default as identity,
    device_name varchar(255);,
    primary key (id);
);
alter table if exists beacon_attributes 
   add constraint FKetmnlsb244lhjo5lxteiwy2n9 
   foreign key (beacon_id); 
   references beacon;

alter table if exists device_active_geofences 
   add constraint FKcwnmkhcbprpdlhtdcev5pobqm 
   foreign key (device_id); 
   references device;

alter table if exists device_asn_configs 
   add constraint FK2kwc0b338ko0ik7amjswsupwd 
   foreign key (device_id); 
   references device;

alter table if exists device_geofences 
   add constraint FK26s5uklcaggr74e84b5bi95ny 
   foreign key (device_id); 
   references device;
alter table if exists device_notifications 
   add constraint FKipv2okwkoyl4nkrp342rtaf5o 
   foreign key (device_id); 
   references device;
