--liquibase formatted sql
-- changeset author:initial version:1

CREATE TABLE credentials (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             safectory_api_cred VARCHAR(255)
);
