-- Liquibase migration file for `User`
CREATE TABLE if not exists users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Liquibase migration file for `Role`
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
                            user_id BIGINT,
                            role_id BIGINT,
                            PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                            CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Liquibase migration file for `Alert`
CREATE TABLE alert (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       position_id BIGINT NOT NULL,
                       message VARCHAR(255) NOT NULL,
                       timestamp TIMESTAMP NOT NULL
);

-- Liquibase migration file for `AnalysisType`
CREATE TABLE analysis_type (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL UNIQUE,
                               description VARCHAR(255),
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Liquibase migration file for `AnalysisConfig`
CREATE TABLE analysis_config (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 key VARCHAR(255) NOT NULL UNIQUE,
                                 value VARCHAR(255) NOT NULL,
                                 data_type VARCHAR(255),
                                 description VARCHAR(255),
                                 analysis_type_id BIGINT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE analysis_config
    ADD CONSTRAINT fk_analysis_type FOREIGN KEY (analysis_type_id) REFERENCES analysis_type(id);

-- Liquibase migration file for `Credentials`
CREATE TABLE credentials (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             safectory_api_cred VARCHAR(255)
);

-- Liquibase migration file for `CronJobConfigEntity`
CREATE TABLE cron_job_config_entity (
                                        job_name VARCHAR(255) PRIMARY KEY,
                                        cron_expression VARCHAR(255),
                                        fixed_rate BIGINT,
                                        enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- Liquibase migration file for `CronJobLog`
CREATE TABLE cron_job_logs (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               job_name VARCHAR(255) NOT NULL,
                               start_time VARCHAR(255),
                               end_time VARCHAR(255),
                               duration_ms BIGINT,
                               status VARCHAR(255),
                               error_message VARCHAR(255)
);

-- Liquibase migration file for `DeviceAnalysis`
CREATE TABLE device_analysis (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 device_id BIGINT,
                                 average_rssi DOUBLE PRECISION,
                                 average_scan_rssi DOUBLE PRECISION,
                                 top_locations TEXT,
                                 devices_with_beacon BIGINT,
                                 devices_without_beacon BIGINT,
                                 timestamp TIMESTAMP
);

-- Liquibase migration file for `DeviceMovementPattern`
CREATE TABLE device_movement_pattern (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         device_id BIGINT,
                                         center_latitude DOUBLE PRECISION NOT NULL,
                                         center_longitude DOUBLE PRECISION NOT NULL,
                                         cluster_size INT NOT NULL,
                                         timestamp TIMESTAMP NOT NULL,
                                         positions_json TEXT
);

-- Liquibase migration file for `LearningMeasurement`
CREATE TABLE learning_measurement (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      wifi_ap VARCHAR(255) NOT NULL,
                                      cnx_time TIMESTAMP NOT NULL,
                                      client_id VARCHAR(255) NOT NULL,
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Liquibase migration file for `LoadHistory`
CREATE TABLE load_history (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              start_date TIMESTAMP NOT NULL,
                              end_date TIMESTAMP NOT NULL,
                              rows_loaded INT NOT NULL,
                              time_taken_ms BIGINT NOT NULL,
                              status VARCHAR(255) NOT NULL,
                              load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Liquibase migration file for `Measurement`
CREATE TABLE measurement (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             valid BOOLEAN NOT NULL,
                             device VARCHAR(255) NOT NULL,
                             time TIMESTAMP NOT NULL,
                             geofences VARCHAR(255),
                             latitude DOUBLE PRECISION NOT NULL,
                             longitude DOUBLE PRECISION NOT NULL,
                             altitude DOUBLE PRECISION,
                             beacon VARCHAR(255),
                             major INT,
                             minor INT,
                             uuid VARCHAR(255),
                             speed DOUBLE PRECISION,
                             attributes TEXT,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Liquibase migration file for `Position`
CREATE TABLE position (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          protocol VARCHAR(255),
                          server_time TIMESTAMP,
                          device_time TIMESTAMP,
                          fix_time TIMESTAMP,
                          outdated BOOLEAN,
                          valid BOOLEAN,
                          latitude DOUBLE PRECISION NOT NULL,
                          longitude DOUBLE PRECISION NOT NULL,
                          event_id BIGINT,
                          device_id BIGINT,
                          scan_rssi INT,
                          rssi INT,
                          beacon_id BIGINT,
                          beacon_name VARCHAR(255),
                          beacon_major INT,
                          beacon_minor INT,
                          beacon_uuid VARCHAR(255),
                          source_device_id BIGINT,
                          device_name VARCHAR(255),
                          speed DOUBLE PRECISION
);

CREATE TABLE position_attributes (
                                     position_id BIGINT,
                                     attribute_name VARCHAR(255),
                                     attribute_value TEXT,
                                     PRIMARY KEY (position_id, attribute_name)
);

-- Liquibase migration file for `PositionSanitized`
CREATE TABLE position_sanitized (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255),
                                    protocol VARCHAR(255),
                                    server_time TIMESTAMP,
                                    device_time TIMESTAMP,
                                    fix_time TIMESTAMP,
                                    outdated BOOLEAN,
                                    valid BOOLEAN,
                                    latitude DOUBLE PRECISION NOT NULL,
                                    longitude DOUBLE PRECISION NOT NULL,
                                    event_id BIGINT,
                                    device_id BIGINT,
                                    scan_rssi INT,
                                    rssi INT,
                                    beacon_id BIGINT,
                                    beacon_name VARCHAR(255),
                                    beacon_major INT,
                                    beacon_minor INT,
                                    beacon_uuid VARCHAR(255),
                                    source_device_id BIGINT,
                                    device_name VARCHAR(255),
                                    speed DOUBLE PRECISION
);

CREATE TABLE position_sanitized_attributes (
                                               position_sanitized_id BIGINT,
                                               attribute_name VARCHAR(255),
                                               attribute_value TEXT,
                                               PRIMARY KEY (position_sanitized_id, attribute_name)
);

-- Liquibase migration file for `ProcessedPosition`
CREATE TABLE processed_position (
                                    unique_key VARCHAR(255) PRIMARY KEY
);

-- Liquibase migration file for `ProcessingCheckpoint`
CREATE TABLE processing_checkpoint (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       last_processed_id BIGINT
);

-- Liquibase migration file for `SimulatedLocation`
CREATE TABLE simulated_location (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    cattle_id VARCHAR(255) NOT NULL,
                                    space_id VARCHAR(255) NOT NULL,
                                    latitude DOUBLE PRECISION NOT NULL,
                                    longitude DOUBLE PRECISION NOT NULL,
                                    start_time TIMESTAMP NOT NULL,
                                    end_time TIMESTAMP NOT NULL
);
