
-- Liquibase formatted SQL
-- changeset your_name:create_simulated_location_table

CREATE TABLE position_sanitized (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          device_id BIGINT,
                          protocol VARCHAR(255),
                          device_time TIMESTAMP WITH TIME ZONE,
                          fix_time TIMESTAMP WITH TIME ZONE,
                          server_time TIMESTAMP WITH TIME ZONE,
                          valid BOOLEAN NOT NULL,
                          latitude FLOAT(53) NOT NULL,
                          longitude FLOAT(53) NOT NULL,
                          speed FLOAT(53) NOT NULL,
                          source_device_id BIGINT,
                          device_name VARCHAR(255),
                          name VARCHAR(255),
                          beacon_uuid VARCHAR(255),
                          beacon_name VARCHAR(255),
                          beacon_id BIGINT,
                          beacon_major INTEGER,
                          beacon_minor INTEGER,
                          rssi INTEGER,
                          scan_rssi INTEGER,
                          outdated BOOLEAN NOT NULL,
                          event_id BIGINT,
                          PRIMARY KEY (id)
);

CREATE TABLE position_sanitized_attributes (
                         position_sanitized_id BIGINT NOT NULL,
                         attribute_name VARCHAR(255) NOT NULL,
                         attribute_value TEXT,
                         PRIMARY KEY (position_sanitized_id, attribute_name)
);